create table if not exists public.confidence_players (
  id bigint generated by default as identity primary key,
  season integer not null,
  player_key text not null,
  player_name text not null,
  pin_hash text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (season, player_key)
);

create table if not exists public.confidence_entries (
  id bigint generated by default as identity primary key,
  season integer not null,
  week integer not null check (week between 1 and 18),
  player_key text not null,
  player_name text not null,
  tiebreaker_total integer not null check (tiebreaker_total between 0 and 200),
  submitted_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (season, week, player_key)
);

create table if not exists public.confidence_picks (
  id bigint generated by default as identity primary key,
  season integer not null,
  week integer not null check (week between 1 and 18),
  player_key text not null,
  game_id text not null,
  team text not null,
  confidence_value integer not null check (confidence_value between 1 and 18),
  updated_at timestamptz default now(),
  unique (season, week, player_key, game_id)
);

create index if not exists confidence_entries_season_week_idx
  on public.confidence_entries (season, week);

create index if not exists confidence_picks_season_week_idx
  on public.confidence_picks (season, week);

create index if not exists confidence_picks_player_idx
  on public.confidence_picks (season, player_key);

alter table public.confidence_players enable row level security;
alter table public.confidence_entries enable row level security;
alter table public.confidence_picks enable row level security;
