create table if not exists public.draft_salary_settings (
  id bigint generated by default as identity primary key,
  season integer not null unique,
  salary_cap integer not null check (salary_cap > 0),
  updated_at timestamptz default now()
);

create table if not exists public.draft_team_values (
  id bigint generated by default as identity primary key,
  season integer not null,
  team text not null,
  salary integer not null check (salary > 0),
  updated_at timestamptz default now(),
  unique (season, team)
);

create index if not exists draft_team_values_season_idx
  on public.draft_team_values (season);

alter table public.draft_salary_settings enable row level security;
alter table public.draft_team_values enable row level security;

insert into public.draft_salary_settings (season, salary_cap)
values (2026, 39500)
on conflict (season) do nothing;

insert into public.draft_team_values (season, team, salary)
values
  (2026, 'BUF', 8000),
  (2026, 'PHI', 7800),
  (2026, 'KC', 7600),
  (2026, 'SF', 7400),
  (2026, 'MIN', 7250),
  (2026, 'BAL', 7050),
  (2026, 'GB', 6850),
  (2026, 'DAL', 6650),
  (2026, 'LAR', 6450),
  (2026, 'SEA', 6300),
  (2026, 'DET', 6150),
  (2026, 'PIT', 6000),
  (2026, 'TB', 5850),
  (2026, 'LAC', 5700),
  (2026, 'CIN', 5550),
  (2026, 'DEN', 5400),
  (2026, 'MIA', 5250),
  (2026, 'NE', 5100),
  (2026, 'HOU', 4950),
  (2026, 'IND', 4800),
  (2026, 'JAX', 4650),
  (2026, 'ATL', 4500),
  (2026, 'WAS', 4350),
  (2026, 'NO', 4200),
  (2026, 'CLE', 4050),
  (2026, 'CHI', 3900),
  (2026, 'TEN', 3750),
  (2026, 'LV', 3600),
  (2026, 'ARI', 3450),
  (2026, 'CAR', 3300),
  (2026, 'NYJ', 3150),
  (2026, 'NYG', 3000)
on conflict (season, team) do nothing;
