create table if not exists public.games (
  id text primary key,
  season integer not null,
  week integer not null,
  game_date text,
  status text,
  away_team text,
  home_team text,
  away_score integer,
  home_score integer,
  winner text,
  loser text,
  margin integer,
  updated_at timestamptz
);

create table if not exists public.draft_players (
  id integer primary key,
  player_name text not null,
  team1 text default '',
  team2 text default '',
  team3 text default '',
  team4 text default '',
  team5 text default '',
  team6 text default '',
  team7 text default '',
  team8 text default '',
  updated_at timestamptz
);

alter table public.games enable row level security;
alter table public.draft_players enable row level security;


create table if not exists public.survivor_picks (
  id bigint generated by default as identity primary key,
  season integer not null,
  week integer not null check (week between 1 and 18),
  player_name text not null,
  player_key text not null,
  team text not null,
  submitted_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (season, week, player_key)
);

create index if not exists survivor_picks_season_week_idx
  on public.survivor_picks (season, week);

create index if not exists survivor_picks_player_idx
  on public.survivor_picks (season, player_key);

alter table public.survivor_picks enable row level security;



create table if not exists public.survivor_players (
  player_key text primary key,
  player_name text not null,
  pin_hash text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.survivor_players enable row level security;


-- NFL Degenerates Pool V2.1 Safe Test Mode
-- Run once in Supabase SQL Editor before deploying V2.1.
-- These tables are completely separate from live pool tables.

create table if not exists public.test_games (
  id text primary key,
  week integer not null,
  away_team text not null,
  home_team text not null,
  away_score integer,
  home_score integer,
  status text not null default 'scheduled',
  updated_at timestamptz default now()
);

create table if not exists public.test_survivor_picks (
  id bigint generated by default as identity primary key,
  player_name text not null,
  player_key text not null,
  week integer not null,
  team text not null,
  updated_at timestamptz default now(),
  unique (player_key, week)
);

create table if not exists public.test_draft_players (
  id bigint generated by default as identity primary key,
  player_name text not null unique,
  team1 text,
  team2 text,
  updated_at timestamptz default now()
);

alter table public.test_games enable row level security;
alter table public.test_survivor_picks enable row level security;
alter table public.test_draft_players enable row level security;
