create table if not exists public.survivor_week_settings (
  id bigint generated by default as identity primary key,
  season integer not null,
  week integer not null check (week between 1 and 18),
  deadline_at timestamptz not null,
  reveal_at timestamptz not null,
  updated_at timestamptz default now(),
  unique (season, week)
);

create index if not exists survivor_week_settings_season_week_idx
  on public.survivor_week_settings (season, week);

alter table public.survivor_week_settings enable row level security;
