-- NFL Degenerates Pool V2.0 Survivor Controls
-- Run once in Supabase SQL Editor before deploying V2.0.

create table if not exists public.survivor_players (
  id bigint generated by default as identity primary key,
  season integer not null,
  player_key text not null,
  player_name text not null,
  pin_hash text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (season, player_key)
);

create index if not exists survivor_players_season_idx
  on public.survivor_players (season);

alter table public.survivor_players enable row level security;
