-- NFL Degenerates Pool V1.9
-- Run this once in Supabase SQL Editor before deploying V1.9.

create table if not exists public.survivor_picks (
  id bigint generated by default as identity primary key,
  season integer not null,
  week integer not null check (week between 1 and 18),
  player_name text not null,
  player_key text not null,
  team text not null,
  submitted_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (season, week, player_key)
);

create index if not exists survivor_picks_season_week_idx
  on public.survivor_picks (season, week);

create index if not exists survivor_picks_player_idx
  on public.survivor_picks (season, player_key);

alter table public.survivor_picks enable row level security;
