-- NFL Degenerates Pool V2.1 Safe Test Mode
-- Run once in Supabase SQL Editor before deploying V2.1.
-- These tables are completely separate from live pool tables.

create table if not exists public.test_games (
  id text primary key,
  week integer not null,
  away_team text not null,
  home_team text not null,
  away_score integer,
  home_score integer,
  status text not null default 'scheduled',
  updated_at timestamptz default now()
);

create table if not exists public.test_survivor_picks (
  id bigint generated by default as identity primary key,
  player_name text not null,
  player_key text not null,
  week integer not null,
  team text not null,
  updated_at timestamptz default now(),
  unique (player_key, week)
);

create table if not exists public.test_draft_players (
  id bigint generated by default as identity primary key,
  player_name text not null unique,
  team1 text,
  team2 text,
  updated_at timestamptz default now()
);

alter table public.test_games enable row level security;
alter table public.test_survivor_picks enable row level security;
alter table public.test_draft_players enable row level security;
