create table if not exists public.forum_topics (
  id bigint generated by default as identity primary key,
  author text not null,
  title text not null,
  message text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  author text not null,
  message text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists forum_topics_created_idx
  on public.forum_topics (created_at desc);

create index if not exists forum_posts_topic_idx
  on public.forum_posts (topic_id, created_at);

alter table public.forum_topics enable row level security;
alter table public.forum_posts enable row level security;
