-- NFL Degenerates V2.13 — Member Accounts
-- Run once in Supabase SQL Editor BEFORE deploying V2.13.

create table if not exists public.member_accounts (
  id bigint generated by default as identity primary key,
  username text not null,
  username_key text not null unique,
  display_name text not null,
  password_hash text not null,
  role text not null default 'MEMBER' check (role in ('MEMBER','COMMISSIONER')),
  active boolean not null default true,
  must_change_password boolean not null default true,
  draft_player_id bigint null,
  survivor_player_key text null,
  confidence_player_key text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz null
);

create index if not exists member_accounts_display_name_idx
  on public.member_accounts (display_name);

create index if not exists member_accounts_draft_player_idx
  on public.member_accounts (draft_player_id);

create index if not exists member_accounts_survivor_key_idx
  on public.member_accounts (survivor_player_key);

create index if not exists member_accounts_confidence_key_idx
  on public.member_accounts (confidence_player_key);

alter table public.member_accounts enable row level security;


-- Tie new forum posts to the authenticated member account while preserving
-- existing V2.11 posts, which remain valid with a NULL member_account_id.
alter table public.forum_topics
  add column if not exists member_account_id bigint null
  references public.member_accounts(id) on delete set null;

alter table public.forum_posts
  add column if not exists member_account_id bigint null
  references public.member_accounts(id) on delete set null;

create index if not exists forum_topics_member_account_idx
  on public.forum_topics (member_account_id);

create index if not exists forum_posts_member_account_idx
  on public.forum_posts (member_account_id);


-- The Flask server accesses this table with the Supabase service key.
-- No public RLS policies are intentionally created.
